env:
  global:
    - CC_TEST_REPORTER_ID=1ec0e82ac7a13e879f71d36abbf09c7c691c71ec58a8b7f74beef6086e3b65db

language: ruby

# 2.0 has only one test not passing
# (TranslationIO::YAMLConversion#get_yaml_data_from_flat_translations works with weird not-escaped code)
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby

gemfile:
  - gemfiles/lowest.gemfile
  - gemfiles/latest.gemfile

matrix:
  exclude:
    - rvm: jruby # Seems to use bundler 2.0 even with before_install commands that worked for other rubies
      gemfile: gemfiles/lowest.gemfile

sudo: false

# https://docs.travis-ci.com/user/languages/ruby/
# To stay on bundler 1 for compatibility with rails 4.1
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    recipients:
      - contact@translation.io
